spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: naikan
      replica-set-name: rs0
  ldap:
    urls: ldap://localhost:389
    base: ou=users,dc=naikan,dc=io
    username: admin
    password: admin
    anonymous-read-only: true
  docker:
    compose:
      file: "./development/docker/compose.yml"
      enabled: true

logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate: DEBUG

naikan:
  security:
    cors:
      allowed-origin-patterns: http://localhost:4200
    ldap:
      user-dn-patterns: uid={0}
      user-search-filter: